##
## AppVeyor
## https://www.appveyor.com/
##
## https://ci.appveyor.com/project/rotators/foclassic/
##

version: "{build}"

# VS 2013 image = VS 2010 build
image:
 - Visual Studio 2013
 - Visual Studio 2017

platform:
 - Win32

matrix:
 allow_failures:
  - image: Visual Studio 2017

skip_commits:
 files:
  - .travis.yml

clone_folder: C:\FOClassic

cache:
 - C:\FOClassic\SDK.Cache -> CMakeLists.txt, Build.cmake, CMake\SelfUpdate.cmake

install:
 - sh: PATH=SDK.Cache/cmake/bin:$PATH
 - cmd: set PATH=SDK.Cache\cmake\bin;%PATH%
 - cmake -P CMake/SelfUpdate.cmake
 - sh: hash -r

build_script:
 - cmake -P Build.cmake

artifacts:
 - path: FOClassic-v*
