##
## AppVeyor
## https://www.appveyor.com/
## https://ci.appveyor.com/project/rotators/foclassic/
##

# https://www.appveyor.com/docs/appveyor-yml/
# https://www.appveyor.com/docs/build-configuration/#build-pipeline

version: "{build}"

# VS 2013 image = VS2010 build
image:
 - Visual Studio 2013
 - Visual Studio 2017

platform:
 - Win32

matrix:
 allow_failures:
  - image: Visual Studio 2017

clone_depth: 50
clone_folder: C:\FOClassic

install:
 - git submodule update --init --recursive

build_script:
 - cmake -P Build.cmake
