##
## AppVeyor
## https://www.appveyor.com/
## https://ci.appveyor.com/project/rotators/foclassic/
##

# https://www.appveyor.com/docs/appveyor-yml/
# https://www.appveyor.com/docs/build-configuration/#build-pipeline

version: "{build}"

# VS 2013 image = VS 2010 build
image:
 - Visual Studio 2013
 - Visual Studio 2017

platform:
 - Win32

matrix:
 allow_failures:
  - image: Visual Studio 2017

clone_folder: C:\FOClassic

install:
 - git submodule update --init --recursive

before_build:
 - sh: git ls-files | while read file; do echo $file; touch -t $(date -jf "%s" $(git log --date=local -1 --format="@%ct" "$file" | cut -b 2-) +%Y%m%d%H%M) "$file"; done

build_script:
 - cmake -P Build.cmake

artifacts:
 - path: SDK\FOClassic-v*
