##
## AppVeyor
## https://www.appveyor.com/
## https://ci.appveyor.com/project/rotators/foclassic/
##

# https://www.appveyor.com/docs/appveyor-yml/
# https://www.appveyor.com/docs/build-configuration/#build-pipeline

version: "{build}"

# VS 2013 image = VS 2010 build
image:
 - Visual Studio 2013
 - Visual Studio 2017

platform:
 - Win32

matrix:
 allow_failures:
  - image: Visual Studio 2017

clone_folder: C:\FOClassic

cache:
 - C:\FOClassic\SDK.Cache -> CMakeLists.txt, Build.cmake, CMake\SelfUpdate.cmake

install:
 - git submodule update --init --recursive
 - set PATH=SDK.Cache\cmake\bin;%PATH%
 - cmake -P CMake\SelfUpdate.cmake

build_script:
 - cmake -P Build.cmake

artifacts:
 - path: FOClassic-v*
