version: "{build}"

image:
 - Visual Studio 2013 # 2010 in disguise
 - Visual Studio 2017

platform:
 - Win32

configuration:
 - Release

clone_depth: 50
clone_folder: C:\FOClassic

matrix:
 allow_failures:
  - image: Visual Studio 2017

install:
 - cd %APPVEYOR_BUILD_FOLDER%
 - git submodule update --init --recursive
 - set

build_script:
 - cmake -P Build.cmake
