language: cpp

matrix:
 include:
  - os: linux
    compiler: g++-4.8
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
      packages:
       - g++-4.8

git:
 depth: false

cache:
 directories:
  - SDK.Cache

install:
 - export PATH=SDK.Cache/cmake/bin:$PATH
 - cmake -P CMake/SelfUpdate.cmake && hash -r

script:
 - cmake -P Build.cmake
