os: linux
sudo: required

git:
 depth: false

matrix:
 include:
  - compiler: g++-4.9
  - compiler: g++-4.8
 allow_failures:
  - compiler: g++-4.9
  - compiler: g++-4.8

cache:
 directories:
  - SDK.Cache

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
 - sudo apt-get update
 - sudo apt-get install -y build-essential linux-libc-dev:i386 ${TRAVIS_COMPILER}-multilib

install:
 - export PATH=SDK.Cache/cmake/bin:$PATH
 - cmake -P CMake/SelfUpdate.cmake && hash -r

script:
 - cmake -P Build.cmake
