sudo: required
language: cpp

matrix:
 include:
  - os: linux
    compiler: g++-4.8
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
      packages:
       - linux-libc-dev:i386
       - g++-4.8-multilib

git:
 depth: false

matrix:
 allow_failures:
  - compiler: g++-4.8

cache:
 directories:
  - SDK.Cache

install:
 - export PATH=SDK.Cache/cmake/bin:$PATH
 - cmake -P CMake/SelfUpdate.cmake && hash -r

script:
 - cmake -P Build.cmake
